language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - nightly

sudo: false

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer --prefer-source install

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

matrix:
  allow_failures:
    - php: nightly
